use crate::input::{Event, InputState, MouseButton};
use crate::js_types::{bodies_to_polygon_arrays, OutgoingEvent, PolygonArray};
use chubby_bunny_core::{Body, BodyId};
use chubby_bunny_svg::BodyMeta;
use nalgebra::Vector2;
use std::collections::{HashMap, VecDeque};
use wasm_bindgen::prelude::*;

/// Event loop and game state management. This struct holds the game implementation,
///  the current state of user input, and the polygon arrays to be rendered on the canvas.
pub struct GameLoop<G: Game> {
    /// The game implementation that defines the game logic and state.
    pub game_impl: Box<G>,
    /// The polygon arrays generated from the bodies to be rendered on the canvas.
    pub polygon_arrays: Vec<PolygonArray>,
    /// The current state of user input. Sadly we're single threaded, so we have to collect all input events here and then pass
    /// them to the game implementation during the update phase.
    pub user_input: InputState,
}

pub trait Game {
    /// Initializes the game state with the given width and height. This is called once when the game starts.
    fn init(&mut self, width: usize, height: usize);
    /// Resets the game state to its initial configuration. This can be called multiple times, for example on resize or on button press.
    fn reset(&mut self, width: f32, height: f32);
    /// Updates the game state based on the incoming user input events and the time delta since the last update. This is called on every animation frame.
    fn update(&mut self, incoming_events: VecDeque<Event>, dt_ms: f32) -> Vec<OutgoingEvent>;
    /// Returns a slice of the bodies to be rendered. This is used to generate the polygon arrays for the canvas.
    fn bodies_to_render(&self) -> &[Body];
    /// Returns a reference to the metadata for the bodies to be rendered. This is used to generate the polygon arrays for the canvas.
    fn meta_data_to_render(&self) -> &HashMap<BodyId, BodyMeta>;
}

impl<G: Game> GameLoop<G> {
    /// Creates a new GameLoop with the given game implementation.
    /// Calls the init method of the game implementation to set up the initial game state.
    pub fn init(&mut self, width: usize, height: usize) {
        self.polygon_arrays.clear();
        self.user_input = InputState::new();
        self.game_impl.init(width, height);
    }

    /// Updates the internal game state, by passing the collected user input events and the time delta to the game implementation's update method.
    /// After the game implementation updates its state, this method generates the polygon arrays for rendering based
    /// on the bodies and metadata provided by the game implementation.
    /// It returns the outgoing events generated by the game implementation, serialized as a JsValue to be sent back to the JavaScript side.
    pub fn update(&mut self, dt_ms: f32) -> Result<JsValue, JsValue> {
        let outgoing_events = self
            .game_impl
            .update(self.user_input.events.drain(..).collect(), dt_ms);
        self.polygon_arrays = bodies_to_polygon_arrays(
            self.game_impl.bodies_to_render().iter(),
            self.game_impl.meta_data_to_render(),
        );
        serde_wasm_bindgen::to_value(&outgoing_events)
            .map_err(|e| JsValue::from_str(&e.to_string()))
    }

    /// Resets the game state to its initial configuration by calling the reset method of the game implementation.
    pub fn reset(&mut self, width: f32, height: f32) {
        self.polygon_arrays.clear();
        self.game_impl.reset(width, height);
    }

    /// Returns the current polygon arrays to be rendered on the canvas, serialized as a JsValue to be sent back to the JavaScript side.
    /// These contain both position and color information for each polygon to be rendered.
    pub fn get_polygon_arrays(&self) -> Result<JsValue, JsValue> {
        serde_wasm_bindgen::to_value(&self.polygon_arrays)
            .map_err(|e| JsValue::from_str(&e.to_string()))
    }

    /// Handles a mouse down event from the browser by recording it in the user input state.
    pub fn mouse_down(&mut self, x: f32, y: f32, mouse_button: MouseButton, time_stamp: f32) {
        self.user_input
            .mouse_down(mouse_button, Vector2::new(x, y), time_stamp);
    }

    /// Handles a mouse up event from the browser by recording it in the user input state.
    pub fn mouse_up(&mut self, x: f32, y: f32, mouse_button: MouseButton, time_stamp: f32) {
        self.user_input
            .mouse_up(mouse_button, Vector2::new(x, y), time_stamp);
    }

    /// Handles a mouse move event from the browser by recording it in the user input state.
    pub fn mouse_move(&mut self, x: f32, y: f32, time_stamp: f32) {
        self.user_input.mouse_move(Vector2::new(x, y), time_stamp);
    }
}
